<section class="section about">
    <a name="about"></a>
    <h1>«VELES» - индикатор для торговли бинарными опционами, построенный только на тех методах, которые проверены
        временем и используются каждым трейдером.</h1>

    <div class="container-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="ab-rect">
                        Простая установка и настройка
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="ab-rect">
                        Используйте любого брокера и котировки
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="ab-rect">
                        Проверенные результаты на протяжении двух лет
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="ab-rect">
                        Высокий гарантированный ITM
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>