<section class="section faq">
    <a name="faq"></a>
    <div class="r-heading">
        Вопрос-ответ
    </div>
    <div class="candy"></div>

    <div class="container-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Какие сроки экспирации?</span><br>
                        Ответ: <span class="reply">Срок экспирации как стандартный одна свеча так и возможны более длинные сроки
экспирации как 3 свечи или 6 свечей (для таймфрейма М5 : 5, 15 и 30 минут).</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">На каком таймфрейме лучше использовать?</span><br>
                        Ответ: <span class="reply">Лучшие таймфреймы М5 и М15, но на М1 так же можно использовать.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
