<section class="section faq">
    <a name="faq"></a>
    <a class="faq-unwrap" href="javascript:faqUnwrap()" title="Развернуть">
        <div class="r-heading">
            Вопрос-ответ <span class="icon icon-circle-down"></span>
        </div>
        <div class="candy"></div>
    </a>

    <div class="container-wrap faq-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Какие сроки экспирации?</span><br>
                        Ответ: <span class="reply">Срок экспирации как стандартный одна свеча так и возможны более длинные сроки
экспирации как 3 свечи или 6 свечей (для таймфрейма М5 : 5, 15 и 30 минут).</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">На каком таймфрейме лучше использовать?</span><br>
                        Ответ: <span
                                class="reply">Лучшие таймфреймы М5 и М15, но на М1 так же можно использовать.</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Сколько активов нужно для торговли?</span><br>
                        Ответ: <span
                                class="reply">Для торговли можно использовать все возможные активы, а так же можно торговать
даже на малом количестве пар. Конкретнее о выборе активов будет сказано в инструкции.</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Как я буду получать уведомления?</span><br>
                        Ответ: <span class="reply">Во время сигнала вы получите звуковой сигнал алерт, а так же указатель на покупку или продажу.</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Какие риски при работе в нестабильные дни?</span><br>
                        Ответ: <span
                                class="reply">Не секрет, что в сильно новостные дни, а так же в первые или послежние недели, в купе с сильными трендовыми движениями любой индикатор может дать просто огромную просадку.
Но Veles устроен таким образом, что даже в такие дни он не будет давать высокорискованных сигналов.</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Как  покажет себя на длинной дистанции?</span><br>
                        Ответ: <span
                                class="reply">Индикатор будет стабильно работать даже через несколько лет. Тем более, что он тестировался не один месяц и даже не один год.</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pan-item">
                        Вопрос: <span class="question">Что если мне нужна будет новая лицензия?</span><br>
                        Ответ: <span
                                class="reply">Если вам придется сменить ПК новую лицензию вы получаете бесплатно.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
