<section class="section indicator-strategy">
    <a name="indicator-strategy"></a>
    <div class="r-heading">
        Стратегия работы индикатора
    </div>
    <div class="candy"></div>

    <img class="indicator-strategy-img" alt="Стратегия работы индикатора" src="strategy.png">

    <div class="container-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="s-info">
                        <div class="perc">80%</div>
                        винрейт
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="s-info">
                        <div class="perc">100+</div>
                        активов для торговли
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="s-info">
                        <div class="perc">+14%</div>
                        к депозиту ежедневно
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="s-info">
                        <div class="perc">50+</div>
                        точный сигналов еженедельно
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
