<section class="section indicator">
    <a name="indicator"></a>
    <div class="r-heading">
        Технология индикатора
    </div>
    <div class="candy"></div>

    <div class="container-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="pan-caption">
                        То что используют трейдеры всего мира <span class="color-1">VELES</span> организует и исполняет
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-1"></div>
                        <div class="progress-caption">Горизонтальные уровни и зоны</div>
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-2"></div>
                        <div class="progress-caption">Профиль рынка</div>
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-3"></div>
                        <div class="progress-caption">Точки пивот и круглые уровни</div>
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-4"></div>
                        <div class="progress-caption">Вертикальные объемы</div>
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-5"></div>
                        <div class="progress-caption">Мультифреймовый анализ</div>
                    </div>
                    <div class="pan-indicator">
                        <div class="progress-bar perc-6"></div>
                        <div class="progress-caption">Скользящие средние и другие динамические уровни</div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="pan-caption">
                        Сигналы индикатора соответствуют всем требованиям
                    </div>
                    <div class="pan-item">Не перерисовывается</div>
                    <div class="pan-item">Сигналы подаются заранее</div>
                    <div class="pan-item">Работает на любом МТ4</div>
                    <div class="pan-item">Упор сделан на точность и надежность</div>
                    <div class="pan-item">Работает в любую торговую сессию</div>
                    <div class="pan-item">Работает на любых таймфреймах</div>
                </div>
            </div>
        </div>
    </div>

</section>
