<section class="section join-us">
    <a name="join-us"></a>
    <div class="r-heading">
        Присоединяйтесь к нам!
    </div>
    <div class="candy"></div>

    <div class="container-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <table class="join-info">
                        <tr>
                            <td class="tb-capt">Индикатор VELES</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Инструкция по торговле</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Техническая поддержка</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Консультация трейдеров</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Лицензия на 2 ПК</td>
                        </tr>
                        <tr>
                            <td class="tb-price">3450</td>
                        </tr>
                        <tr>
                            <td class="tb-order">
                                <a href="#">ЗАКАЗАТЬ</a>
                            </td>
                        </tr>
                    </table>
                </div>

                <div class="col-md-6">
                    <table class="join-info right">
                        <tr>
                            <td class="tb-capt">Индикатор VELES</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Инструкция по торговле</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Техническая поддержка</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Консультация трейдеров</td>
                        </tr>
                        <tr>
                            <td class="tb-capt">Лицензия на 4 ПК</td>
                        </tr>
                        <tr>
                            <td class="tb-price">6150</td>
                        </tr>
                        <tr>
                            <td class="tb-order">
                                Пока не доступно
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

</section>
