<section class="section main-video">
    <a name="main-video"></a>
    <video controls>
        <source src="Индикатор-ВЕЛЕС.mp4" type="video/mp4">
        <!-- MP4 для Safari, IE9, iPhone, iPad, Android, и Windows Phone 7 -->
        <source src="Индикатор-ВЕЛЕС.webm" type="video/webm"><!-- WebM/VP8 для Firefox4, Opera, и Chrome -->
        <source src="Индикатор-ВЕЛЕС.ogv" type="video/ogg">
        <!-- Ogg/Vorbis для старых версий браузеров Firefox и Opera -->
        <!--<object data="video.swf" type="application/x-shockwave-flash">&lt;!&ndash; добавляем видеоконтент для устаревших браузеров, в которых нет поддержки элемента video &ndash;&gt;
            <param name="movie" value="video.swf">
        </object>-->
    </video>
</section>