<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">VELES</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
            <!--<li class="nav-item active">
                <a class="nav-link" href="#main-video">Домой</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#about">О нас</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#indicator">Индикатор</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#indicator-strategy">Стратегия</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#join-us">Присоединяйтесь</a>
            </li>-->
            <li class="nav-item active">
                <a class="nav-link" href="#main-video">Интро</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#indicator">Технологии</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#indicator-strategy">Стратегия</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#join-us">Заказать</a>
            </li>
        </ul>
    </div>
</nav>